const {Router} = require('express');
const {usuariosGet} = require('../controllers/Users');
const {usuariosPost} = require('../controllers/Users');
const {usuariosPut} = require('../controllers/Users');
const {usuariosPatch} = require('../controllers/Users');
const {usuariosDelete} = require('../controllers/Users');
const router = Router();
router.get('/', usuariosGet); 
router.post('/', usuariosPost);
router.put('/', usuariosPut);
router.patch('/', usuariosPatch);
router.delete('/', usuariosDeleten);
module.exports = router;